### ISSUE TITLE
Add dynamic rescaling to vega plots

### ISSUE THREAD

**Issue by gromdimon** [bihealth/reev#106]
**Is your feature request related to a problem? Please describe.**
Currently all the presented plots have static dimensions. However, users may have different monitors, what causes imperfect alligning. 

**Describe the solution you'd like**
Add a feature to adapt height and width of the plot to the window size.

**Describe alternatives you've considered**
N/A

**Additional context**
The Vuetify breakpoints might be useful here.

**Comment by gromdimon** [comment]
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "width": "container",
  "height": "container",
  "data": {"url": "data/cars.json"},
  "mark": "bar",
  "encoding": {
    "x": {"field": "Origin"},
    "y": {"aggregate": "count", "title": "Number of Cars"}
  }
}
```

**Comment by gromdimon** [comment]
https://vega.github.io/vega-lite/docs/size.html#

**Comment by holtgrewe** [comment]
I think the limitation is the following:

![image](https://github.com/bihealth/reev/assets/521780/81e103bd-b330-4001-b47b-a0e6b9f1bba4)
