### ISSUE TITLE
Show Clinvar data for Structure Variants

### ISSUE THREAD

**Issue by gromdimon** [bihealth/reev#108]
**Is your feature request related to a problem? Please describe.**
Currently SV details page has only information about genes and GenBrowser. However, it's possible to present ClinVar and Genotype Call data. 

**Describe the solution you'd like**
Implement `SvDetailsClinvar.vue` and `SvDetailsGenotypeCall.vue` cards.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by holtgrewe** [comment]
Solved in #239
