### ISSUE TITLE
Update ACMG for SVs

### ISSUE THREAD

**Issue by gromdimon** [bihealth/reev#115]
**Describe the bug**
Right now information used in ACMG classification card for SV might be wrong. So this is unacceptable for users and should be fixed.

**To Reproduce**
1. Go to SV page
2. Investigate ACNG card

**Expected behavior**
All the information should be reliable.

**Additional context**
TODO:
- [ ] Add tests for phoenix backend calls
- [ ] Check criteria info
- [ ] Add structure to criteria listing
- [ ] Check conflicting evidences

**Comment by holtgrewe** [comment]
We use AutoCNV here. We will fix the issue when we roll out our own AutoCNV replacement.
