### ISSUE TITLE
Wrong REVEL score for nonsense variant

### ISSUE THREAD

**Issue by sczakihl** [bihealth/reev#126]
**Describe the bug**
REVEL is depicted as -infinity / benign very strong for nonsense variant, where REVEL should not be available.

**To Reproduce**
1. Go to 'https://reev.cubi.bihealth.org/variant/chr7:42007251:G:A/grch37'
3. Scroll down to 'Precomputed Scores'

**Expected behavior**
No REVEL score should be displayed for nonsense variants. See e.g.:
https://reev.cubi.bihealth.org/variant/chr2:219747090:C:A/grch37

**Screenshots**
Wrong REVEL for chr7:42007251:G:A
![grafik](https://github.com/bihealth/reev/assets/94172011/ec75b459-a84d-4f24-8955-ed2e89364e26)

What it should look like e.g. for chr2:219747090:C:A
![grafik](https://github.com/bihealth/reev/assets/94172011/c147b772-d912-4216-b4da-cffa2540a72f)

**Comment by gromdimon** [comment]
Previous solution didn't solve the problem

**Comment by gromdimon** [comment]
Previous commet seems to be invalid due to testing an old version.
