### ISSUE TITLE
Docker build fails due to large js chunks

### ISSUE THREAD

**Issue by gromdimon** [bihealth/reev#181]
**Describe the bug**
Docker started failling building image with the following warning:
```
(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 11.44s
```

**To Reproduce**
1. Go to `frontend/`
2. Run `npm run build`
3. See warning

**Expected behavior**
Currently we have custon vite setting `chunkSizeWarningLimit`, but we should find an optimal solution.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by holtgrewe** [comment]
Here is how to do this in the Vue Router Docs:

- https://router.vuejs.org/guide/advanced/lazy-loading.html#Lazy-Loading-Routes

```
// replace
// import UserDetails from './views/UserDetails'
// with
const UserDetails = () => import('./views/UserDetails.vue')

const router = createRouter({
  // ...
  routes: [
    { path: '/users/:id', component: UserDetails }
    // or use it directly in the route definition
    { path: '/users/:id', component: () => import('./views/UserDetails.vue') },
  ],
})
```
