### ISSUE TITLE
Consistency in UI Design on Home Page

### ISSUE THREAD

**Issue by gromdimon** [bihealth/reev#215]
**Problem Statement:**
The Home Page of the Reev application currently exhibits a lack of consistent UI design, similar to the issue previously identified on the Profile page (refer to issue #214). This inconsistency is particularly evident in aspects such as layout, component design, and visual styling, leading to a disjointed user experience.

**Proposed Solution:**
To address this, we propose a comprehensive overhaul of the Home Page's UI, aiming to align it with the newly established standards set forth in issue #214. This will involve revising the CSS styling and employing Vuetify components to ensure uniformity and coherence in design. Our goal is to create a seamless and aesthetically pleasing interface that aligns with the improvements made on the Profile page.

**Alternative Solutions:**
N/A

**Additional Information:**
This issue is a continuation of our ongoing efforts to enhance the UI across the entire Reev platform, following the principles and standards established in the recent refactor of the Profile page (issue #214).

**Comment by gromdimon** [comment]
After merging #239 #255 #256 #264 we just need to clean up the design and make minor corrections. Under this comment there should be a list of desired changes. Below you can find an image of the current design status. 
Ping @holtgrewe @mikkonie 

![image](https://github.com/bihealth/reev/assets/86564271/30341d9a-708a-4185-9762-79ef72776e7e)

**Comment by mikkonie** [comment]
Some minor issues I detected with the current version of the home page:

1. **Search bar overflow** (screenshot 1)
    - The search bar overflows past the width of the following element towards the right and is no longer centered in the browser. This is not exactly serious but appears as a bug.
    - The elements should either share the same width or appear horizontally centered to each other.
2. **Search icon** (screenshot 1)
    - The rocket icon is fun, but I'm not sure if it's a clear control for "initiate search" for the average user.
    - I myself first thought it was some extra option or something similar.
    - Perhaps a more traditional icon or a labeled button would be better? This is mostly a matter of taste of course.
3. **Example alignment** (screenshot 2)
    - The third example in "structural variants" is misaligned.
4. **Top bar links and padding** (screenshot 3)
    - Generally you want to leave a bit of "breathing room" between your active links/elements and the edge of the viewport.
    - Especially the combination of rounded shape and zero padding sticks out. Zero padding is ok with straight boxes, but if going for the rounded look, I'd add a bit of padding on the edges.
    - Doesn't have to be much if you're aiming for screen real estate, a few pixels is better than nothing.

Screenshot 1:

![home_search](https://github.com/bihealth/reev/assets/11211145/0e0fe45a-affd-4cd2-b4ae-28413c6d739a)

Screenshot 2:

![home_variants](https://github.com/bihealth/reev/assets/11211145/0fa0b339-1a7b-4a61-956e-0e24b7b15f9b)

Screenshot 3:

![home_top_bar](https://github.com/bihealth/reev/assets/11211145/31b5e682-74e5-44f7-af26-97efdded21c4)

**Comment by holtgrewe** [comment]
Hm, I cannot confirm (1)

![image](https://github.com/bihealth/reev/assets/521780/4155ea1d-2f44-465b-b4e6-199373e070df)

Replacing (2)

![image](https://github.com/bihealth/reev/assets/521780/22b2f4a0-0003-4b3c-8859-edbfab8a92ca)

I could not reproduce (3) on Linux with Firefox or Chrome even when reducing the window width.

(4) I'm adjusting a couple of things, so spacing is more comfortable now.

**Comment by holtgrewe** [comment]
This is how my local version looks now.

![image](https://github.com/bihealth/reev/assets/521780/b0d39dd1-f040-4680-afe2-c027dcc0d56b)
