### ISSUE TITLE
Consistency in UI Design on Gene Information Page

### ISSUE THREAD

**Issue by gromdimon** [bihealth/reev#216]
**Problem Statement:**
The Gene Information page within the Reev application currently displays significant inconsistencies in its UI design. This issue mirrors the challenges we've addressed on other pages, such as the Profile and Home pages (refer to issues #214 and #215). These inconsistencies are evident in the layout, typography, color schemes, and interactive elements, resulting in a non-uniform user experience that detracts from the overall usability and aesthetic appeal of the page.

**Proposed Solution:**
To remedy this, we propose a detailed revamp of the UI elements on the Gene Information page. The focus will be on standardizing the design elements in line with the UI improvements implemented on the Profile and Home pages. This will include updates to CSS styling, and the integration of Vuetify components to achieve a cohesive look and feel. Our objective is to ensure that the Gene Information page not only meets but exceeds user expectations in terms of design consistency and navigational ease.

**Alternative Solutions:**
N/A

**Additional Information:**
This issue is part of our broader initiative to harmonize the UI across the entire Reev platform, building upon the successful UI upgrades previously implemented (as seen in issues #214 and #215).

**Comment by gromdimon** [comment]
As described in #215 we just need to clean up the design and make minor corrections. Under this comment there should be a list of desired changes. Below you can find an image of the current design status.
Ping @holtgrewe @mikkonie

![image](https://github.com/bihealth/reev/assets/86564271/5cddd5ca-68c5-4cce-b333-bd33b625078a)

**Comment by gromdimon** [comment]
**Wanted changes**

**Comment by holtgrewe** [comment]
We should make the page consistent with the new homepage.

![image](https://github.com/bihealth/reev/assets/521780/702687af-6999-4145-ac9a-a392d132f7d5)

**Comment by holtgrewe** [comment]
I'm working on it. @gromdimon one thing that I'm doing now is using global vuetify configuration for getting a flat appearance together with default corners.
