### ISSUE TITLE
Consistency in UI Design on Variant Information Page

### ISSUE THREAD

**Issue by gromdimon** [bihealth/reev#217]
**Problem Statement:**
The Variant Information page within the Reev application currently displays significant inconsistencies in its UI design. This issue mirrors the challenges we've addressed on other pages, such as the Profile and other pages (refer to issues #214  #215 #216 ). These inconsistencies are evident in the layout, typography, color schemes, and interactive elements, resulting in a non-uniform user experience that detracts from the overall usability and aesthetic appeal of the page.

**Proposed Solution:**
To remedy this, we propose a detailed revamp of the UI elements on the Variant Information page. The focus will be on standardizing the design elements in line with the UI improvements implemented on other pages. This will include updates to CSS styling, and the integration of Vuetify components to achieve a cohesive look and feel. Our objective is to ensure that the Variant Information page not only meets but exceeds user expectations in terms of design consistency and navigational ease.

**Alternative Solutions:**
N/A

**Additional Information:**
This issue is part of our broader initiative to harmonize the UI across the entire Reev platform, building upon the successful UI upgrades previously implemented (as seen in issues #214  #215 #216).

**Comment by gromdimon** [comment]
As described in #215 we just need to clean up the design and make minor corrections. Under this comment there should be a list of desired changes. 
Ping @holtgrewe @mikkonie

**Comment by gromdimon** [comment]
**Wanted changes**

**Comment by holtgrewe** [comment]
**production screenshot**

![image](https://github.com/bihealth/reev/assets/521780/233668e6-46d0-4b39-971b-32f9765d47dd)

**patch screenshot**

![image](https://github.com/bihealth/reev/assets/521780/aadaf2b7-8d51-469c-a8e6-7fcdfcd0b8d2)

**Comment by mikkonie** [comment]
One major issue here is that the leftmost and rightmost controls on the page get pushed outside of the screen if viewport is even slightly more narrow than 1920px. I'm not looking for responsivity fit for a mobile device, but that seems to be a harsh requirement :)

Note the screenshot where most the leftmost control bar is being hidden and the top right corner dropdown is already fully invisible.

If there is content e.g. embedded from other apps which overflows so badly, it should be contained within its own scrollable element in such a case. Or even overflow from the viewport, that's ok, but it shouldn't hide controls.

![variant_overflow](https://github.com/bihealth/reev/assets/11211145/9743474f-8dba-4322-9271-8ba923994cfb)
