### ISSUE TITLE
Consistency in UI Design on static Pages

### ISSUE THREAD

**Issue by gromdimon** [bihealth/reev#219]
**Problem Statement:**
Some static pages (About, Contact, Privacy Policy, Tems of Use) within the Reev application currently displays significant inconsistencies in its UI design. This issue mirrors the challenges we've addressed on other pages, such as the Profile and other pages (refer to issues #214 #215 #216 #217 #218). These inconsistencies are evident in the layout, typography, color schemes, and interactive elements, resulting in a non-uniform user experience that detracts from the overall usability and aesthetic appeal of the page.

**Proposed Solution:**
To remedy this, we propose a detailed revamp of the UI elements on the static pages. The focus will be on standardizing the design elements in line with the UI improvements implemented on the Profile and other pages. This will include updates to CSS styling, and the integration of Vuetify components to achieve a cohesive look and feel. Our objective is to ensure that this static pages not only meets but exceeds user expectations in terms of design consistency and navigational ease.

**Alternative Solutions:**
N/A

**Additional Information:**
This issue is part of our broader initiative to harmonize the UI across the entire Reev platform, building upon the successful UI upgrades previously implemented (as seen in issues #214 #215 #216 #217 #218).

**Comment by gromdimon** [comment]
As described in #215 we just need to clean up the design and make minor corrections. Under this comment there should be a list of desired changes.
Ping @holtgrewe @mikkonie

**Comment by holtgrewe** [comment]
1. This appears to be a vuetify reactivity issue, if you open it several times, it will flush right on the menu and not truncate any more. There apparently is no way to align it with vuetify v3.

... will continue working on this later

**Comment by mikkonie** [comment]
Some notes on the bookmarks view:

1. **Missing label**
    - It seems to be possible to have a bookmark without a label. See screenshot.
    - I'm not quite sure how I did this and can't reproduce immediately, but all I did was bookmark examples from the home view.
2. **Visual nitpicks**
    - The links are styled as buttons. This is a bit confusing, as they are links. Maybe they could be styled like e.g. the "variant tools" links in the variant view? This would be more consistent.
    - The trash buttons should be the same height as the link elements. Now they're a lot bigger, which looks inconsistent and creates a lot of unneded margin between elements.
    - The "Your bookmarks" title has a colon behind it, while e.g. similar page titles in the main user profile view do not.

![bookmarks](https://github.com/bihealth/reev/assets/11211145/8703e4c8-752a-4736-ab2f-23cc86578220)

**Comment by gromdimon** [comment]
Implemented in #283
