### ISSUE TITLE
Text in plots is not readable in dark mode

### ISSUE THREAD

**Issue by gromdimon** [bihealth/reev#284]
**Describe the bug**
Some text is hardly readable in plots in dark mode. This is due font color, which is somehow hardcoded in vega-light plots.

**To Reproduce**
1. Go to any page with plots
2. Change theme to dark mode
3. Encounter bug

**Expected behavior**
The text should be readable in dark mode.

**Screenshots**
![image](https://github.com/bihealth/reev/assets/86564271/a13a123b-ad70-40f2-8d72-57a199646786)
![image](https://github.com/bihealth/reev/assets/86564271/5b216c6a-7b26-47fb-8634-64b7560472a7)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by holtgrewe** [comment]
A first resolution would just the set background color appropriately.
