### ISSUE TITLE
VariantValidator integration is broken

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/reev#292]
**Describe the bug**
For some reason, the variant validator integration is broken.

**To Reproduce**
1. Go to any seqvar detail page
2. Submit to variant validator
3. See error

**Expected behavior**
Most of the time it should work.

**Additional context**
N/A

**Comment by gromdimon** [comment]
I've mentioned this issue in #272 . This problem seems to be not on our site)

**Comment by holtgrewe** [comment]
Actually, it was. Fixing in #376.
