### ISSUE TITLE
GTEX Expression displayed incorrectly

### ISSUE THREAD

**Issue by sczakihl** [bihealth/reev#316]
**Describe the bug**
The plot of GTEX expression data seems broken: There appears to be a shift in the assignment of tissue names to the corresponding expression in the data:
Color and expression values missalign. e.g. "Bladder" is colored green as "Brain" and then again on the other end of brain data the last "Brain" is already colored yellow.  Also the respective TPM values are off in the same vein. This seems to result from an introduction of "undefined" at the very beginning not existing in the GTEX portal causing a frameshift in all following assignments. 

**To Reproduce**
1. Go to 'https://reev.cubi.bihealth.org/seqvar/grch37-X-77245290-G-C?orig=GRCh37-X-77245290-G-C'
3. Scroll down to 'Expression'

**Expected behavior**
Displayed data should correspond to data shown in the GTEX link-out. Colors should fit the respective tissue groups.

**Screenshots**
REEV Expression:
![grafik](https://github.com/bihealth/reev/assets/94172011/778d0329-54fb-4d3b-8a45-a3cd3f268b2d)

Versus GTEX for the same gene:
![grafik](https://github.com/bihealth/reev/assets/94172011/f8d69223-45c5-420c-89ed-f955974b5d88)

**Comment by holtgrewe** [comment]
Already fixed via https://github.com/bihealth/annonars/pull/333 and we were missing the fixed dataset.

**Comment by holtgrewe** [comment]
Updating data, restarting annonars server and here we go.

![image](https://github.com/bihealth/reev/assets/521780/f66de183-d2aa-48e2-964c-14f01a8c4a91)
