### ISSUE TITLE
Documentation does not build

### ISSUE THREAD

**Issue by gromdimon** [bihealth/reev#368]
**Describe the bug**
Documentation does not build.

**To Reproduce**
N/A

**Expected behavior**
It should build.

**Additional context**
N/A

**Comment by holtgrewe** [comment]
Having a built PDF would be nice to attach to the manuscript. Reopening.

**Comment by holtgrewe** [comment]
The root cause was missing `.. footbibliography::` lines at the bottom of `.rst` files that had `:footcite:` in them.
