### ISSUE TITLE
Add introductory text to the quickstart section.

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/reev#398]
**Is your feature request related to a problem? Please describe.**
User guidance in the quickstart tutorial should be improved.

**Describe the solution you'd like**
Add a introductory text section.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sczakihl** [comment]
Suggested the following introduction:

We have developed REEV (Review, Evaluate and Explain Variants) to help clinicians and researchers in rare disease genetics with an open and free platform to explore comprehensive information about genes as well as sequence and structural variants. REEV is designed to help you to quickly yet comprehensively record all the important information on a variant and, on the basis of this, to evaluate it on the basis of the ACMG criteria. To this end, REEV also integrates methods that allow users to (semi-)automatically fill the individual ACMG criteria sections to facilitate interpretation.
Here, we provide a quick start as well as a full tutorial guiding you through the process on reviewing and evaluating genes and variants with the help of REEV.
