### ISSUE TITLE
Improve the description of advantages of a login

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/reev#400]
**Is your feature request related to a problem? Please describe.**
Currently, the documentation only mentions necessity of logins in the ClinVar submissions sections.

**Describe the solution you'd like**
Properly document this and not only mention it in the ClinVar submissions section.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sczakihl** [comment]
Added a 'User Login' section to the tutorial:

-------------------
User login
-------------------

All of the above is possible without any login. Beyond this, a login to REEV offers additional helpful features. 

With creating a login you can:

- upload case specific information which can be helpful in evaluating your variant. E.g., you can add phenotypic information on your case by providing the corresponding HPO terms (see also above in the OMIM and HPO section of the sequence variant tutorial). On having provided HPO terms, a gene-to-phenotype rank will be provided to help you evaluate how well your patient’s phenotype and the known gene-disease association fit one another.

- bookmark genes and variants of interest to return to them at a later time point

- submit your evaluated variant to ClinVar (see ClinVar submission section)
