### ISSUE TITLE
InterVar prediction not working properly

### ISSUE THREAD

**Issue by sczakihl** [bihealth/reev#443]
**Describe the bug**
Sometimes the intervar prediction works, sometimes it doesn't, I don't quite understand why and when. e.g. this variant actually works: chrX:77245290:G:C But if I look up this frameshift variant beforehand: chr4:113568536:G:GA, which also doesn't work, then the other one doesn't work either, after reloading the page via the shift key and reloading, it works.

**To Reproduce**
1. Go to 'reev'
2. test above mentioned SNVs
3. Scroll down to 'clinical significance'

**Expected behavior**
InterVar prediction should be provided. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows / MacOS
 - Browser: Firefox, Edge / Firefox

**Comment by holtgrewe** [comment]
@sczakihl please confirm that it works now

**Comment by sczakihl** [comment]
@holtgrewe yes, working now
