### ISSUE TITLE
SplicePredictions: show most pathogenic in overview instead of alphabetic order

### ISSUE THREAD

**Issue by sczakihl** [bihealth/reev#444]
**Describe the bug**
SplicePredictions shows just first in alphabetic order in overview

**To Reproduce**
1. Go to 'reev'
2. enter variant: NM_016356.4:c.349-2A>G
3. Scroll down to 'scores'
4. MMSplice_acceptorintron stead of mmsp_aceptor as most pathogenic prediction

**Expected behavior**
show most pathogenic in overview instead of alphabetic order

**Screenshots**
![grafik](https://github.com/bihealth/reev/assets/94172011/0d90418a-4e60-4368-8429-4329832f0f28)

**Comment by holtgrewe** [comment]
**Root Cause Analysis**
Currently, the largest score is displayed but we should display the score with largest absolute value.

**Comment by holtgrewe** [comment]
fixed

![Uploading image.png…]()
