### ISSUE TITLE
Splice prediction scores missing for intronic variant

### ISSUE THREAD

**Issue by sczakihl** [bihealth/reev#446]
**Describe the bug**
Splice prediction scores missing for intronic variant

**To Reproduce**
1. Go to 'reev'
2. entervariant  as genomic chrX:129156859:C:G or cDNA level NM_001379451.1(BCORL1):c.3608-13C>G
3. Scroll down to 'scores'

**Expected behavior**
mmsplice and spliceai scores should be provided 

**Screenshots**
![grafik](https://github.com/bihealth/reev/assets/94172011/34db903d-1af5-415f-815f-11b16e131dfe)

**Comment by holtgrewe** [comment]
**Root Cause Analysis**
Scores currently not shown if position not in dbNSFP, although splice scores are available even then.

**Comment by sczakihl** [comment]
@holtgrewe yes, working fine now
