### ISSUE TITLE
Props are not setted while mounting in tests

### ISSUE THREAD

**Issue by gromdimon** [bihealth/reev#46]
**Describe the bug**
Most of tests use the following type of mounting:
```
mount(
    {
      template: '<v-app><AboutView /></v-app>'
    },
    ...
  )
```
This is the only way to render vuetify components rightly. However in tests for components with obligate props there's an error:
props are not passed in the component itself.

**To Reproduce**
See tests in `components/__tests__/*`. Try to change mounting option to one above and encounter vue warnings.

**Expected behavior**
Props should be setted.

**Comment by gromdimon** [comment]
**Update**
It seems that props are correctly set to component with mounting like:
```
mount(AboutView,
    {
          props: ...
    }
)
```

And this art of mounting is specified in original docs. However, due to veutify we should mount it through `<v-app>` tag, which requires setting props as `<AboutView :props=props>`, which causes another errors, such as:
```
[Vue warn]: Property "gene" was accessed during render but is not defined on instance.
TypeError: Cannot convert object to primitive value
```

**Comment by holtgrewe** [comment]
Should be fixed now?

**Comment by gromdimon** [comment]
Missed your previous comment @holtgrewe . Yes, it's fixed.
