### ISSUE TITLE
Integrate ClinVar per-gene information

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/reev#53]
**Is your feature request related to a problem? Please describe.**
ClinVar is a useful database and we should display more information from there once available via annonars.

**Describe the solution you'd like**
Once annonars provides the data, display:

- number of variants per effect and clinical significance
- display variants per significance and population frequency
- display lollypop graph of variants along the genome

**Describe alternatives you've considered**
N/A

**Additional context**
Needs update of annonars.

**Comment by gromdimon** [comment]
I think this options were implemented in #62 . If I'm wrong @holtgrewe feel free to reopen an issue!
