### ISSUE TITLE
Fix triggering events in vuetify components tests

### ISSUE THREAD

**Issue by gromdimon** [bihealth/reev#79]
**Describe the bug**
There is an issue while testing my Vue3+vuetify+vitest components. It seems that clicking buttons, selecting drop-down items, pasting information into text fields, and other interactions are not triggering the expected events. While I can set values to components, I'm unable to properly test different emits and events.

To illustrate the problem, @gromdimon  created a minimal project available here: [GitHub Repository](https://github.com/gromdimon/testing-vuetify.git).

**To Reproduce**
See [GitHub Repository](https://github.com/gromdimon/testing-vuetify.git). 

**Expected behavior**
The manipulations in content should trigger events.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu22.04
 - Vue3
 - Vuetify
 - vitest

**Additional context**

**Comment by holtgrewe** [comment]
Works properly in this repo:

- https://github.com/holtgrewe/vuetify3-vue3-test

**Comment by holtgrewe** [comment]
Subsumed by #355

**Comment by holtgrewe** [comment]
The code in #363 features properly working events in components.
